[package]
name = "linode-worker"
version = "0.0.1"
edition = "2018"
authors = ["Rivet Gaming, LLC <developer@rivet.gg>"]
license = "Apache-2.0"

[dependencies]
rivet-convert = { path = "../../../../lib/convert" }
chirp-client = { path = "../../../../lib/chirp/client" }
chirp-worker = { path = "../../../../lib/chirp/worker" }
rivet-health-checks = { path = "../../../../lib/health-checks" }
rivet-metrics = { path = "../../../../lib/metrics" }
rivet-runtime = { path = "../../../../lib/runtime" }
util-linode = { package = "rivet-util-linode", path = "../util" }

cluster = { path = "../../cluster" }

[dependencies.sqlx]
git = "https://github.com/rivet-gg/sqlx"
rev = "08d6e61aa0572e7ec557abbedb72cebb96e1ac5b"
default-features = false

[dev-dependencies]
chirp-worker = { path = "../../../../lib/chirp/worker" }
