[package]
name = "job-run-get"
version = "0.0.1"
edition = "2021"
authors = ["Rivet Gaming, LLC <developer@rivet.gg>"]
license = "Apache-2.0"

[dependencies]
rivet-operation = { path = "../../../../../lib/operation/core" }
chirp-client = { path = "../../../../../lib/chirp/client" }
chrono = "0.4"
prost = "0.10"
nomad-client = "0.0.9"
util-job = { package = "rivet-util-job", path = "../../../job/util" }

[dependencies.sqlx]
git = "https://github.com/rivet-gg/sqlx"
rev = "08d6e61aa0572e7ec557abbedb72cebb96e1ac5b"
default-features = false

[dev-dependencies]
chirp-worker = { path = "../../../../../lib/chirp/worker" }

faker-job-run = { path = "../../../faker/ops/job-run" }
nomad-util = { path = "../../../../../lib/nomad-util" }
