[package]
name = "cluster-get-for-game"
version = "0.0.1"
edition = "2018"
authors = ["Rivet Gaming, LLC <developer@rivet.gg>"]
license = "Apache-2.0"

[dependencies]
chirp-client = { path = "../../../../../lib/chirp/client" }
prost = "0.10"
rivet-operation = { path = "../../../../../lib/operation/core" }
util-cluster = { package = "rivet-util-cluster", path = "../../util" }

[dependencies.sqlx]
version = "0.7"
default-features = false

[dev-dependencies]
chirp-worker = { path = "../../../../../lib/chirp/worker" }
