[service]
name = "api-internal-monolith"
essential = true
priority = 70

[runtime]
kind = "rust"

# Has no mounts, internal only
[api]

[resources.single-node]
cpu = 50
memory = 64

[resources.distributed]
cpu = 1000
memory = 512
