[package]
name = "tier-list"
version = "0.0.1"
edition = "2021"
authors = ["Rivet Gaming, LLC <developer@rivet.gg>"]
license = "Apache-2.0"

[dependencies]
chirp-client = { path = "../../../../../lib/chirp/client" }
chirp-workflow = { path = "../../../../../lib/chirp-workflow/core" }
prost = "0.10"
rivet-operation = { path = "../../../../../lib/operation/core" }

cluster = { path = "../../../cluster" }
linode = { path = "../../../linode" }

[dev-dependencies]
chirp-worker = { path = "../../../../../lib/chirp/worker" }
