[package]
name = "test-ds-echo"
version = "0.1.0"
edition = "2021"

[dependencies]
anyhow = "1.0"
futures-util = { version = "0.3", features = ["sink"] }
hyper = { version = "0.14", features = ["server"] }
reqwest = "0.11"
tokio = { version = "1.29", features = ["full"] }
tokio-util = "0.7.11"

[profile.release]
opt-level = 'z'
lto = true
codegen-units = 1

