[package]
name = "api-servers"
version = "0.0.1"
authors = ["Rivet Gaming, LLC <developer@rivet.gg>"]
edition = "2021"
license = "Apache-2.0"

[dependencies]
api-helper = { path = "../../../lib/api-helper/build" }
chirp-client = { path = "../../../lib/chirp/client" }
rivet-operation = { path = "../../../lib/operation/core" }
chrono = "0.4"
http = "0.2"
hyper = { version = "0.14", features = ["server", "http1", "stream", "tcp"] }
rivet-api = { path = "../../../sdks/full/rust" }
rivet-cache = { path = "../../../lib/cache/build" }
rivet-claims = { path = "../../../lib/claims" }
rivet-health-checks = { path = "../../../lib/health-checks" }
rivet-convert = { path = "../../../lib/convert" }
rivet-pools = { path = "../../../lib/pools" }
s3-util = { path = "../../../lib/s3-util" }
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
tokio = { version = "1.29" }
tracing = "0.1"
tracing-futures = "0.2"
tracing-subscriber = { version = "0.3", default-features = false, features = ["fmt", "json", "ansi"] }
url = "2.2.2"
uuid = { version = "1", features = ["v4"] }

build-create = { path = "../../pkg/build/ops/create" }
build-get = { path = "../../pkg/build/ops/get" }
game-namespace-get = { path = "../../pkg/game/ops/namespace-get" }
build-list-for-game = { path = "../../pkg/build/ops/list-for-game" }
cluster-datacenter-get = { path = "../../pkg/cluster/ops/datacenter-get" }
cluster-datacenter-list = { path = "../../pkg/cluster/ops/datacenter-list" }
cluster-datacenter-resolve-for-name-id = { path = "../../pkg/cluster/ops/datacenter-resolve-for-name-id" }
cluster-get = { path = "../../pkg/cluster/ops/get" }
cluster-get-for-game = { path = "../../pkg/cluster/ops/get-for-game" }
game-version-get = { path = "../../pkg/game/ops/version-get" }
cluster-list = { path = "../../pkg/cluster/ops/list" }
cluster-resolve-for-name-id = { path = "../../pkg/cluster/ops/resolve-for-name-id" }
ds-server-create = { path = "../../pkg/ds/ops/server-create" }
ds-server-list-for-game = { path = "../../pkg/ds/ops/server-list-for-game" }
ds-server-delete = { path = "../../pkg/ds/ops/server-delete" }
ds-server-get = { path = "../../pkg/ds/ops/server-get" }
user-identity-get = { path = "../../pkg/user-identity/ops/get" }
game-get = { path = "../../pkg/game/ops/get" }
token-revoke = { path = "../../pkg/token/ops/revoke" }
upload-complete = { path = "../../pkg/upload/ops/complete" }
upload-get = { path = "../../pkg/upload/ops/get" }
user-get = { path = "../../pkg/user/ops/get" }
user-team-list = { path = "../../pkg/user/ops/team-list" }

[dev-dependencies]
rivet-connection = { path = "../../../lib/connection" }
reqwest = "0.11"

cdn-namespace-domain-create = { path = "../../pkg/cdn/ops/namespace-domain-create" }
cloud-namespace-token-development-create = { path = "../../pkg/cloud/ops/namespace-token-development-create" }
cloud-namespace-token-public-create = { path = "../../pkg/cloud/ops/namespace-token-public-create" }
cloud-service-game-token-create = { path = "../../pkg/cloud/ops/game-service-token-create" }
faker-build = { path = "../../pkg/faker/ops/build" }
faker-game = { path = "../../pkg/faker/ops/game" }
faker-game-namespace = { path = "../../pkg/faker/ops/game-namespace" }
faker-game-version = { path = "../../pkg/faker/ops/game-version" }
faker-region = { path = "../../pkg/faker/ops/region" }
game-get = { path = "../../pkg/game/ops/get" }
region-get = { path = "../../pkg/region/ops/get" }
