[package]
name = "upload-worker"
version = "0.0.1"
edition = "2021"
authors = ["Rivet Gaming, LLC <developer@rivet.gg>"]
license = "Apache-2.0"

[dependencies]
chirp-worker = { path = "../../../../lib/chirp/worker" }
chirp-client = { path = "../../../../lib/chirp/client" }
rivet-health-checks = { path = "../../../../lib/health-checks" }
rivet-metrics = { path = "../../../../lib/metrics" }
rivet-runtime = { path = "../../../../lib/runtime" }
s3-util = { path = "../../../../lib/s3-util" }

[dependencies.sqlx]
git = "https://github.com/rivet-gg/sqlx"
rev = "08d6e61aa0572e7ec557abbedb72cebb96e1ac5b"
default-features = false

[dev-dependencies]
chirp-worker = { path = "../../../../lib/chirp/worker" }

upload-get = { path = "../ops/get" }
upload-prepare = { path = "../ops/prepare" }
