[package]
name = "foo-worker"
version = "0.0.1"
edition = "2021"
authors = ["Rivet Gaming, LLC <developer@rivet.gg>"]
license = "Apache-2.0"

[dependencies]
chirp-workflow = { path = "../../../../lib/chirp-workflow/core" }
serde = { version = "1.0.198", features = ["derive"] }

user-get = { path = "../../user/ops/get" }
