name: pre-init
description: Set up Nix and Bolt

# TODO: Composite actions don't support defaults
# defaults:
#   run:
#     # Enable fail-fast behavior
#     shell: bash -e {0}

inputs:
  SCCACHE_AWS_SECRET_ACCESS_KEY:
    required: true
  SCCACHE_AWS_ACCESS_KEY_ID:
    required: true
  OP_SERVICE_ACCOUNT_TOKEN:
    required: true

runs:
  using: composite

  steps:
    # MARK: Cache
    - name: Nix Cache
      uses: actions/cache@v3.3.1
      with:
        key: ${{ runner.os }}-nix-${{ hashfiles('./shell.nix', './nix/**/*.nix') }}
        path: ${{ env.store }}
        restore-keys: |
          ${{ runner.os }}-nix-${{ hashfiles('./shell.nix', './nix/**/*.nix') }}
          ${{ runner.os }}-nix-

    # We can't use the GitHub cache because it has a max size of 10 GB
    - name: Enable sccache
      shell: bash -e {0}
      run: |
        # Expose sccache config for all future calls of nix-shell, which configures sccache respectively
        echo 'USE_SCCACHE=1' >> $GITHUB_ENV
        echo 'SCCACHE_BUCKET=rivet-sccache' >> $GITHUB_ENV
        echo 'SCCACHE_ENDPOINT=https://2a94c6a0ced8d35ea63cddc86c2681e7.r2.cloudflarestorage.com/rivet-sccache' >> $GITHUB_ENV
        echo 'SCCACHE_REGION=auto' >> $GITHUB_ENV
        echo 'AWS_SECRET_ACCESS_KEY=${{ inputs.SCCACHE_AWS_SECRET_ACCESS_KEY }}' >> $GITHUB_ENV
        echo 'AWS_ACCESS_KEY_ID=${{ inputs.SCCACHE_AWS_ACCESS_KEY_ID }}' >> $GITHUB_ENV

    # MARK: Nix
    - uses: cachix/install-nix-action@v22
      with:
        nix_path: nixpkgs=channel:nixos-23.05
        extra_nix_config: "store = ${{ env.store }}\n"

    # Build initial shell, all future calls to nix-shell will be fast
    - name: Build Shell
      shell: bash -e {0}
      run: nix-shell --pure --run "echo 'Built shell'"

    # MARK: Bolt
    - name: Pull Config
      shell: bash -e {0}
      env:
        OP_SERVICE_ACCOUNT_TOKEN: ${{ inputs.OP_SERVICE_ACCOUNT_TOKEN }}
      # Cannot use --pure `https://github.com/NixOS/nixpkgs/issues/66716`
      run: |
        nix-shell --run "bolt config pull -y ci --op-namespace-path 'op://Engineering/ice6g6zdnag4lxl5d3dcs7jj64/config' --op-secrets-path 'op://Engineering/ice6g6zdnag4lxl5d3dcs7jj64/secrets'"

    # Delete old Bolt binaries in order to fall back to the Nix-built binary
    - name: Remove Old Bolt Builds
      shell: bash -e {0}
      run: rm -f target/debug/bolt target/release/bolt
