[service]
name = "cluster"

[runtime]
kind = "rust"

[package]

[secrets]
"rivet/api_traefik_provider/token" = {}
"cloudflare/terraform/auth_token" = { optional = true }
"ssh/server/private_key_openssh" = {}

[databases]
db-cluster = {}
