[package]
name = "user-dev-worker"
version = "0.0.1"
edition = "2021"
authors = ["Rivet Gaming, LLC <developer@rivet.gg>"]
license = "Apache-2.0"

[dependencies]
chirp-client = { path = "../../../../lib/chirp/client" }
chirp-worker = { path = "../../../../lib/chirp/worker" }

game-get = { path = "../../game/ops/get" }
team-member-list = { path = "../../team/ops/member-list" }
