[service]
name = "cluster-fix-tls"

[runtime]
kind = "rust"

[secrets]
"rivet/api_traefik_provider/token" = {}
"cloudflare/terraform/auth_token" = { optional = true }
"ssh/server/private_key_openssh" = {}

[headless]
singleton = true
