[package]
name = "team-invite-worker"
version = "0.0.1"
edition = "2021"
authors = ["Rivet Gaming, LLC <developer@rivet.gg>"]
license = "Apache-2.0"

[dependencies]
chirp-worker = { path = "../../../../lib/chirp/worker" }
chirp-client = { path = "../../../../lib/chirp/client" }
rivet-health-checks = { path = "../../../../lib/health-checks" }
rivet-metrics = { path = "../../../../lib/metrics" }
rivet-runtime = { path = "../../../../lib/runtime" }
chrono = "0.4"

team-member-list = { path = "../../team/ops/member-list" }
team-user-ban-get = { path = "../../team/ops/user-ban-get" }

[dependencies.sqlx]
git = "https://github.com/rivet-gg/sqlx"
rev = "08d6e61aa0572e7ec557abbedb72cebb96e1ac5b"
default-features = false

[dev-dependencies]
chirp-worker = { path = "../../../../lib/chirp/worker" }
