[package]
name = "linode-server-destroy"
version = "0.0.1"
edition = "2018"
authors = ["Rivet Gaming, LLC <developer@rivet.gg>"]
license = "Apache-2.0"

[dependencies]
chirp-client = { path = "../../../../../lib/chirp/client" }
rivet-operation = { path = "../../../../../lib/operation/core" }
reqwest = { version = "0.11", features = ["json"] }
util-cluster = { package = "rivet-util-cluster", path = "../../../cluster/util" }
util-linode = { package = "rivet-util-linode", path = "../../util" }

cluster-datacenter-get = { path = "../../../cluster/ops/datacenter-get" }

[dependencies.sqlx]
git = "https://github.com/rivet-gg/sqlx"
rev = "08d6e61aa0572e7ec557abbedb72cebb96e1ac5b"
default-features = false

[dev-dependencies]
chirp-worker = { path = "../../../../../lib/chirp/worker" }

linode-server-provision = { path = "../server-provision" }
